name: Update Subscription

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"


permissions:
  contents: write


jobs:

  update:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install requirements
        run: |
          pip install requests pyyaml


      - name: Update V2Ray
        run: |
          python merge_v2ray.py


      - name: Split V2Ray
        run: |
          python split_v2ray.py


      - name: Update Clash
        run: |
          python merge_clash.py


      - name: Update Singbox
        run: |
          python merge_singbox.py


      - name: Commit changes
        run: |

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git diff --cached --quiet || git commit -m "Auto Update Subscription"

          git push
